#!/bin/bash

sudo cp -r out tmp
cd out
sudo setfacl --restore ../perm.acl
sudo find . -print0 | sudo cpio -o --format=newc --null > ../archive.cpio
cd ..
sudo rm -rf out
mv tmp out

echo "[*]Archive created -> archive.cpio"
